#1:
  source: #2:
    content_for_non_file: ":module _Values\n  :fun example\n    0\n    -0\n    36\n    -36\n    1_234_567_890\n    0xfab0_9FAB\n    0b1000_1000\n    36.6\n    -36.6\n    36e0\n    36E3\n    36.6666e0\n    36.6666E3\n    36.6666e+3\n    36.6666E-3\n    \"foo\"\n    b\"bar\"\n    \"\x01\x02\x03\"\n    \"\u2764\"\n    \"\U0001fa01\"\n    'f'\n    '\0'\n    '\x01'\n    '\u2764'\n    '\U0001fa01'\n    \"compose string a \(\n      99\n    ) \(100) final\"\n    \"compose string b \(\n      99\n    ) \(100)\"\n    b\"\(99)\(100)\"\n    \"\\n        Hello, \\n      World\\n    !\\n    \"\n    b\"\\n      \x00\x11\x22\x33\x44\x55\x66\x77\\n      \x88\x99\xaa\xbb\xcc\xdd\xee\xff\\n    \"\n"
  declares: #3:
    0: #4:
      terms: #5:
        0: #6:
          position: #7:
            source: #2...
            offset: 1
            size: 6
            row: 1
            column: 2
          name: "module"
        1: #8:
          position: #9:
            source: #2...
            offset: 8
            size: 7
            row: 1
            column: 9
          name: "_Values"
      body: #10:
    1: #11:
      terms: #12:
        0: #13:
          position: #14:
            source: #2...
            offset: 19
            size: 3
            row: 2
            column: 4
          name: "fun"
        1: #15:
          position: #16:
            source: #2...
            offset: 23
            size: 7
            row: 2
            column: 8
          name: "example"
      body: #17:
        terms: #18:
          0: #19:
            position: #20:
              source: #2...
              offset: 35
              size: 1
              row: 3
              column: 5
            positive_integer: 0
          1: #21:
            position: #22:
              source: #2...
              offset: 41
              size: 2
              row: 4
              column: 5
            negative_integer: 0
          2: #23:
            position: #24:
              source: #2...
              offset: 48
              size: 2
              row: 5
              column: 5
            positive_integer: 36
          3: #25:
            position: #26:
              source: #2...
              offset: 55
              size: 3
              row: 6
              column: 5
            negative_integer: 36
          4: #27:
            position: #28:
              source: #2...
              offset: 63
              size: 13
              row: 7
              column: 5
            positive_integer: 1234567890
          5: #29:
            position: #30:
              source: #2...
              offset: 81
              size: 11
              row: 8
              column: 5
            positive_integer: 4205879211
          6: #31:
            position: #32:
              source: #2...
              offset: 97
              size: 11
              row: 9
              column: 5
            positive_integer: 136
          7: #33:
            position: #34:
              source: #2...
              offset: 113
              size: 4
              row: 10
              column: 5
            floating_point: 36.6
          8: #35:
            position: #36:
              source: #2...
              offset: 122
              size: 5
              row: 11
              column: 5
            floating_point: -36.6
          9: #37:
            position: #38:
              source: #2...
              offset: 132
              size: 4
              row: 12
              column: 5
            floating_point: 36.0
          10: #39:
            position: #40:
              source: #2...
              offset: 141
              size: 4
              row: 13
              column: 5
            floating_point: 3.6e4
          11: #41:
            position: #42:
              source: #2...
              offset: 150
              size: 9
              row: 14
              column: 5
            floating_point: 36.6666
          12: #43:
            position: #44:
              source: #2...
              offset: 164
              size: 9
              row: 15
              column: 5
            floating_point: 36666.6
          13: #45:
            position: #46:
              source: #2...
              offset: 178
              size: 10
              row: 16
              column: 5
            floating_point: 36666.6
          14: #47:
            position: #48:
              source: #2...
              offset: 193
              size: 10
              row: 17
              column: 5
            floating_point: 0.0366666
          15: #49:
            position: #50:
              source: #2...
              offset: 208
              size: 5
              row: 18
              column: 5
            string: "foo"
          16: #51:
            position: #52:
              source: #2...
              offset: 218
              size: 6
              row: 19
              column: 5
            string_with_prefix: #
              prefix: #53:
                position: #54:
                  source: #2...
                  offset: 218
                  size: 1
                  row: 19
                  column: 5
                value: "b"
              string: "bar"
          17: #55:
            position: #56:
              source: #2...
              offset: 229
              size: 14
              row: 20
              column: 5
            string: "\x01\x02\x03"
          18: #57:
            position: #58:
              source: #2...
              offset: 248
              size: 8
              row: 21
              column: 5
            string: "\xe2\x9d\xa4"
          19: #59:
            position: #60:
              source: #2...
              offset: 261
              size: 12
              row: 22
              column: 5
            string: "\xf0\x9f\xa8\x81"
          20: #61:
            position: #62:
              source: #2...
              offset: 278
              size: 3
              row: 23
              column: 5
            character: 102
          21: #63:
            position: #64:
              source: #2...
              offset: 286
              size: 4
              row: 24
              column: 5
            character: 0
          22: #65:
            position: #66:
              source: #2...
              offset: 295
              size: 6
              row: 25
              column: 5
            character: 1
          23: #67:
            position: #68:
              source: #2...
              offset: 306
              size: 8
              row: 26
              column: 5
            character: 10084
          24: #69:
            position: #70:
              source: #2...
              offset: 319
              size: 12
              row: 27
              column: 5
            character: 129537
          25: #71:
            position: #72:
              source: #2...
              offset: 336
              size: 49
              row: 28
              column: 5
            string_compose: #
              terms: #73:
                0: #74:
                  position: #75:
                    source: #2...
                    offset: 355
                    size: 16
                    row: 28
                    column: 24
                  string: "compose string a "
                1: #76:
                  position: #77:
                    source: #2...
                    offset: 355
                    size: 16
                    row: 28
                    column: 24
                  group: #78:
                    position: #79:
                      source: #2...
                      offset: 355
                      size: 16
                      row: 28
                      column: 24
                    style: SaviProto.AST.Group.Style.Paren
                    terms: #80:
                      0: #81:
                        position: #82:
                          source: #2...
                          offset: 363
                          size: 2
                          row: 29
                          column: 7
                        positive_integer: 99
                2: #83:
                  position: #84:
                    source: #2...
                    offset: 373
                    size: 5
                    row: 30
                    column: 8
                  string: " "
                3: #85:
                  position: #86:
                    source: #2...
                    offset: 373
                    size: 5
                    row: 30
                    column: 8
                  group: #87:
                    position: #88:
                      source: #2...
                      offset: 373
                      size: 5
                      row: 30
                      column: 8
                    style: SaviProto.AST.Group.Style.Paren
                    terms: #89:
                      0: #90:
                        position: #91:
                          source: #2...
                          offset: 374
                          size: 3
                          row: 30
                          column: 9
                        positive_integer: 100
                4: #92:
                  position: #93:
                    source: #2...
                    offset: 337
                    size: 47
                    row: 28
                    column: 6
                  string: " final"
          26: #94:
            position: #95:
              source: #2...
              offset: 390
              size: 43
              row: 31
              column: 5
            string_compose: #
              terms: #96:
                0: #97:
                  position: #98:
                    source: #2...
                    offset: 409
                    size: 16
                    row: 31
                    column: 24
                  string: "compose string b "
                1: #99:
                  position: #100:
                    source: #2...
                    offset: 409
                    size: 16
                    row: 31
                    column: 24
                  group: #101:
                    position: #102:
                      source: #2...
                      offset: 409
                      size: 16
                      row: 31
                      column: 24
                    style: SaviProto.AST.Group.Style.Paren
                    terms: #103:
                      0: #104:
                        position: #105:
                          source: #2...
                          offset: 417
                          size: 2
                          row: 32
                          column: 7
                        positive_integer: 99
                2: #106:
                  position: #107:
                    source: #2...
                    offset: 427
                    size: 5
                    row: 33
                    column: 8
                  string: " "
                3: #108:
                  position: #109:
                    source: #2...
                    offset: 427
                    size: 5
                    row: 33
                    column: 8
                  group: #110:
                    position: #111:
                      source: #2...
                      offset: 427
                      size: 5
                      row: 33
                      column: 8
                    style: SaviProto.AST.Group.Style.Paren
                    terms: #112:
                      0: #113:
                        position: #114:
                          source: #2...
                          offset: 428
                          size: 3
                          row: 33
                          column: 9
                        positive_integer: 100
          27: #115:
            position: #116:
              source: #2...
              offset: 438
              size: 14
              row: 34
              column: 5
            string_compose: #
              prefix: #117:
                position: #118:
                  source: #2...
                  offset: 438
                  size: 1
                  row: 34
                  column: 5
                value: "b"
              terms: #119:
                0: #120:
                  position: #121:
                    source: #2...
                    offset: 441
                    size: 4
                    row: 34
                    column: 8
                  group: #122:
                    position: #123:
                      source: #2...
                      offset: 441
                      size: 4
                      row: 34
                      column: 8
                    style: SaviProto.AST.Group.Style.Paren
                    terms: #124:
                      0: #125:
                        position: #126:
                          source: #2...
                          offset: 442
                          size: 2
                          row: 34
                          column: 9
                        positive_integer: 99
                1: #127:
                  position: #128:
                    source: #2...
                    offset: 446
                    size: 5
                    row: 34
                    column: 13
                  group: #129:
                    position: #130:
                      source: #2...
                      offset: 446
                      size: 5
                      row: 34
                      column: 13
                    style: SaviProto.AST.Group.Style.Paren
                    terms: #131:
                      0: #132:
                        position: #133:
                          source: #2...
                          offset: 447
                          size: 3
                          row: 34
                          column: 14
                        positive_integer: 100
          28: #134:
            position: #135:
              source: #2...
              offset: 457
              size: 45
              row: 35
              column: 5
            string: "Hello, World!"
          29: #136:
            position: #137:
              source: #2...
              offset: 507
              size: 89
              row: 40
              column: 5
            string_with_prefix: #
              prefix: #138:
                position: #139:
                  source: #2...
                  offset: 507
                  size: 1
                  row: 40
                  column: 5
                value: "b"
              string: "\x00\x11\"3DUfw\x88\x99\xaa\xbb\xcc\xdd\xee\xff"
