#1:
  declares: #2:
    0: #3:
      terms: #4:
        0: #5:
          name: "module"
        1: #6:
          name: "_Values"
      body: #7:
    1: #8:
      terms: #9:
        0: #10:
          name: "fun"
        1: #11:
          name: "example"
      body: #12:
        terms: #13:
          0: #14:
            positive_integer: 0
          1: #15:
            negative_integer: 0
          2: #16:
            positive_integer: 36
          3: #17:
            negative_integer: 36
          4: #18:
            positive_integer: 1234567890
          5: #19:
            positive_integer: 4205879211
          6: #20:
            positive_integer: 136
          7: #21:
            floating_point: 36.6
          8: #22:
            floating_point: -36.6
          9: #23:
            floating_point: 36.0
          10: #24:
            floating_point: 3.6e4
          11: #25:
            floating_point: 36.6666
          12: #26:
            floating_point: 36666.6
          13: #27:
            floating_point: 36666.6
          14: #28:
            floating_point: 0.0366666
          15: #29:
            string: "foo"
          16: #30:
            string_with_prefix: #
              string: "b"
              prefix: #31:
                value: "bar"
          17: #32:
            string: "\x01\x02\x03"
          18: #33:
            string: "\xe2\x9d\xa4"
          19: #34:
            character: 102
          20: #35:
            character: 0
          21: #36:
            character: 1
          22: #37:
            character: 10084
