name: Savi
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - crystal: "1.10.1"
            os: ubuntu-20.04
            deps: sudo apt-get install -y capnproto libgc-dev
          - crystal: "1.10.1"
            os: macos-12 # upgrade to macos-13 when available
            deps: brew install libgc capnp
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: ${{matrix.deps}}

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Full CI Suite
        run: make ci
